### ISSUE TITLE
Dilithium BinaryUnmarshaler runtime error

### ISSUE THREAD

**Issue by dhrubabasu** [cloudflare/circl#164]
This code:
```go
package main

import (
	"github.com/cloudflare/circl/sign/dilithium/mode4"
)

func main() {
	_, sk, _ := mode4.GenerateKey(nil)

	var key *mode4.PrivateKey
	bytes, _ := sk.MarshalBinary()
	key.UnmarshalBinary(bytes)
}
```

yields:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x10b4906]

goroutine 1 [running]:
github.com/cloudflare/circl/sign/dilithium/mode4/internal.(*PrivateKey).Unpack(0x0, 0xc000144118)
	/go/pkg/mod/github.com/cloudflare/circl@v1.0.1-0.20201014173823-2cc7fe033cbd/sign/dilithium/mode4/internal/dilithium.go:115 +0x26
github.com/cloudflare/circl/sign/dilithium/mode4.(*PrivateKey).Unpack(...)
	/go/pkg/mod/github.com/cloudflare/circl@v1.0.1-0.20201014173823-2cc7fe033cbd/sign/dilithium/mode4/dilithium.go:87
github.com/cloudflare/circl/sign/dilithium/mode4.(*PrivateKey).UnmarshalBinary(0x0, 0xc000145068, 0xf10, 0xf10, 0x0, 0x0)
	/go/pkg/mod/github.com/cloudflare/circl@v1.0.1-0.20201014173823-2cc7fe033cbd/sign/dilithium/mode4/dilithium.go:142 +0xa5
main.main()
	/main.go:12 +0x94
exit status 2
```

**Comment by dhrubabasu** [comment]
Nevermind, `key` should be of type `mode4.PrivateKey`, not `*mode4.PrivateKey`

**Comment by bwesterb** [comment]
Your original also would have worked if you'd have allocated key, i.e.:

```go
package main

import (
	"github.com/cloudflare/circl/sign/dilithium/mode4"
)

func main() {
	_, sk, _ := mode4.GenerateKey(nil)

	var key *mode4.PrivateKey
        key = new(mode4.PrivateKey)
	bytes, _ := sk.MarshalBinary()
	key.UnmarshalBinary(bytes)
}
```
